matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        chrome: stable
      language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
      env: MP_TARGET=COMMON
      script: ./gradlew reaktive:check reaktive-annotations:check reaktive-test:check utils:check rxjava2-interop:check rxjava3-interop:check coroutines-interop:check -DMP_TARGET=$MP_TARGET
    - os: osx
      osx_image: xcode10.2
      language: java
      env: MP_TARGET=IOS
      script: ./gradlew reaktive:check reaktive-annotations:check reaktive-test:check utils:check coroutines-interop:check -DMP_TARGET=$MP_TARGET
    - os: linux
      language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
      env: MP_TARGET=META
      script: true
install: echo 'org.gradle.jvmargs=-Xmx4g -XX:MaxPermSize=1g -Dkotlin.compiler.execution.strategy="in-process"' >> gradle.properties
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/nodejs/
    - $HOME/.gradle/yarn/
    - $HOME/.konan/
    - build/js/node_modules
deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew bintrayUpload -DMP_TARGET=$MP_TARGET -Pbintray_user=$BINTRAY_USER -Pbintray_key=$BINTRAY_KEY
  on:
    tags: true
