[versions]
kotlin = "1.9.22"
kotlinx-coroutines = "1.8.0"
detekt = "1.22.0"

[libraries]
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations", version.ref = "kotlin" }

kotlinx-compatibility = "org.jetbrains.kotlinx:binary-compatibility-validator:0.13.2"
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

android-plugin = "com.android.tools.build:gradle:8.0.2"

androidx-appcompat = "androidx.appcompat:appcompat:1.4.2"
androidx-constraintLayout = "androidx.constraintlayout:constraintlayout:1.1.3"

jmh-plugin = "me.champeau.jmh:jmh-gradle-plugin:0.7.0"

rxjava2 = "io.reactivex.rxjava2:rxjava:2.2.21"
rxjava3 = "io.reactivex.rxjava3:rxjava:3.1.6"

shadow = "gradle.plugin.com.github.johnrengelman:shadow:7.1.2"

detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-ktlint = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
